---
- name: Validate the log file
  stat:
    path: "{{ log_file }}"
  register: log_state

- name: Create the log file
  file:
    path: "{{ log_file }}"
    state: touch
  when: log_state.stat.exists == false

- debug:
    msg: "{{ date }} Ansible Job was triggered by application - {{ application_name }} as {{ hook_type }} hook in clusters {{ target_clusters }}."

- name: Added log message to file
  lineinfile:
    path: "{{ log_file }}"
    line: "{{ date }} Ansible Job was triggered by application - {{ application_name }} as {{ hook_type }} hook in clusters {{ target_clusters }}."