---
- name: Validate the log file
  stat:
    path: "{{ log_file }}"
  register: log_state

- name: Create the log file
  file:
    path: "{{ log_file }}"
    state: touch
  when: log_state.stat.exists == false