---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: postjob
spec:
  tower_auth_secret: ansible-tower
  job_template_name: Logger
  extra_vars:
    application_name: mariadb
    hook_type: post