apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-argocd
spec:
  destination:
    name: local-cluster
  project: demo-project-argocd
  source:
    path: 04.Application_Lifecycle/demo-argocd/mariadb-resources
    repoURL: https://github.com/michaelkotelnikov/rhacm-workshop
    targetRevision: single-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
